### ISSUE TITLE
Current serializer adds another unnecessary root element

### ISSUE THREAD

**Issue by qoobaa** [qoobaa/fakturama#5]
So the current DB schema has been changed. The settings object was previously stored under:

`:user_id/settings/default`

now it seems to be stored in:

`:user_id/settings/default/settings`

It'd be a good idea to keep the old schema if possible. I experimented with the `DS.RestSerializer`, but I haven't managed to fix it yet. Do you have any idea how to solve this issue, @lowski?

**Comment by lowski** [comment]
@qoobaa I've tried to keep the schema as it was.

I've checked this by running app locally and when I save the settings, the request goes to:

```
https://:database_id.firebaseio.com/:user_id/settings/default.json?auth=token
```

If we don't want to keep data under `settings` object I believe we would need to create a new adapter for settings and modify `createRecord`, `findRecord` and `updateRecord` methods to correctly convert the formats. We could also try to override `serialize` and `normalizeResponse` methods in the serializer.

Actually I using serializers instead of overriding methods in adapter is more Ember way - I was suppose to refactor it but once I got this working I forgot to come back to this.

I will try to take a look at this issue and get back to you.

**Comment by qoobaa** [comment]
I've just created a new "staging" environment for testing, and it looks like this:

![image](https://user-images.githubusercontent.com/10659/34569855-584a587e-f16a-11e7-9f31-1394c7a18394.png)

**Comment by qoobaa** [comment]
I can't take a screenshot of the old version, because I can't log in to the old development console anymore (which sucks a lot), but you can check the old schema using data export button on production (it dumps the whole `:used_id` object). If we're thinking about deploying the new code on the old DB, we'd need to keep the old format.

**Comment by qoobaa** [comment]
What I've found so far is: we could create a `serializers/firebase.js` for Firebase communication, it just needs a `defaultSerializer: "firebase"` property in the application adapter to make it work. But extending the default `DS.RESTSerializer` doesn't work for me (I tried to overwrite e.g. `serializeIntoHash` method). I suspect we'd need to create a serializer by extending `DS.JSONSerializer` instead.

**Comment by lowski** [comment]
> If we're thinking about deploying the new code on the old DB, we'd need to keep the old format.

I totally understand. I must missed the format incompatibility for that. I will take a look at this and get back to you.

I believe this quick fix should work but I would like to go over serializers and adapters again as I think the overall code could be improved. However I would opt to use [emberfire](https://github.com/firebase/emberfire) eventually instead of such custom implementation. WDYT?

**Comment by qoobaa** [comment]
I'm not sure about using Emberfire. I haven't used it since 2014, it was rather bad then. Let's try to fix the updated version - it should be easier to maintain it afterwards.

**Comment by lowski** [comment]
I agree, let's fix the app before any further changes.
